# My config of alacritty, most probably barebones

window: 
  padding:
    x: 5
    y: 5

  dynamic_padding: true
  opacity: 1.0

  title: Alacritty

  dynamic_title: true

  class:
    instance: Alacritty
    general: Alacritty

  decorations_theme_variant: None

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: OverpassM Nerd Font 
    style: Regular

  bold:
    family: OverpassM Nerd Font 
    style: Bold 

  italic:
    family: OverpassM Nerd Font 
    style: Italic

  bold_italic:
    family: OverpassM Nerd Font Propo
    style: SemiBold 

  size: 10.0
  builtin_box_drawing: true

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '#f5f3ef'
    foreground: '#171421'
    # no dim
  
  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  selection:
    text: CellBackground
    background: CellForeground

  normal:
    black:   '#171421'
    red:     '#c01c28'
    green:   '#26a269'
    yellow:  '#a2734c'
    blue:    '#12488b'
    magenta: '#a347ba'
    cyan:    '#2aa1b3'
    white:   '#d0cfcc'

  bright:
    black:   '#5e5c64'
    red:     '#f66151'
    green:   '#33d17a'
    yellow:  '#e9ad0c'
    blue:    '#2a7bde'
    magenta: '#c061cb'
    cyan:    '#33c7de'
    white:   '#ffffff'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true 

cursor:
  style:
    shape: Block
  unfocused_hollow: true

live_config_reload: true
working_directory: None
