#!/bin/bash
set -e

cancel_string='Cancel'
logout_string='Logout'
restart_string='Restart'
shutdown_string='Shutdown'
options_string="$cancel_string\n$logout_string\n$restart_string\n$shutdown_string"

prompt='SESSION_EXIT_OPTIONS'
result=$(printf $options_string | rofi -dmenu -p $prompt -i)

case $result in
	$logout_string)
		i3-msg exit
	exit 0;;

	$restart_string)
		systemctl -i reboot
	exit 0;;

	$shutdown_string)
		systemctl -i poweroff
	exit 0;;
esac
