#!/bin/bash
set -e

if [[ $# -ne 1 ]]; then
	echo "$0: Expected 1 argument, got $#."
	exit 1
fi

ws1="1: Main/Browsing"
ws2="2: Terminal"
ws3="3: Dev"
ws4="4: Sandbox"
ws5="5: Documents"
ws6="6: Unnamed"
ws7="7: Presentation"
ws8="8: Discord"
ws9="9: Work"
ws10="10: Utils"

case $1 in
1)
	i3-msg workspace $ws1
	firefox &
	;;

2)
	i3-msg workspace $ws2
	alacritty &
	;;

3)
	i3-msg workspace $ws3
	restfox &
	;;

4)
	i3-msg workspace $ws4
	Godot_v4* &
	;;

5)
	i3-msg workspace $ws5
	libreoffice &
	;;

# add some more stuff, or rofi cycle here
8)
	i3-msg workspace $ws8
	flatpak run dev.vencord.Vesktop
	;;

9)
	i3-msg workspace $ws9
	flatpak run one.ablaze.floorp &
	;;

0)
	i3-msg workspace $ws10
	obsidian &
	;;
esac
